import { Public_Sans } from "next/font/google";
import "./globals.css";
import { ReduxStoreProvider } from "@/providers/ReduxStoreProvider";
import { ReactNode } from "react";
import { ThemeProvider } from "@mui/material";
import theme from "@/providers/MUITheme";

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-publicSans",
});

export const metadata = {
  title: "Seven Seas Network (Dev)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <ThemeProvider theme={theme}>
          <ReduxStoreProvider>{children}</ReduxStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
